version: '3.7'
services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: voyage2246
      MYSQL_DATABASE: projeto
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      projeto_network:
        ipv4_address: 172.16.238.10

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      projeto_network:
        ipv4_address: 172.16.238.20

networks:
  projeto_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24