"""adding models hotel 2

Revision ID: 8bd241e11b37
Revises: 
Create Date: 2023-07-31 13:24:59.426780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd241e11b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('celular', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('img_perfil_base64',  sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_celular'), 'users', ['celular'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nome'), 'users', ['nome'], unique=False)
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoritos_id'), 'favoritos', ['id'], unique=False)
    op.create_index(op.f('ix_favoritos_id_hotel'), 'favoritos', ['id_hotel'], unique=False)
    op.create_index(op.f('ix_favoritos_id_usuario'), 'favoritos', ['id_usuario'], unique=False)
    op.create_table('galeria_hotel',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.Column('imagem_base64', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galeria_hotel_id'), 'galeria_hotel', ['id'], unique=False)
    op.create_index(op.f('ix_galeria_hotel_id_hotel'), 'galeria_hotel', ['id_hotel'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sobre', sa.String(length=500), nullable=True),
    sa.Column('localizacaoLat', sa.String(length=255), nullable=True),
    sa.Column('localizacaoLong', sa.String(length=255), nullable=True),
    sa.Column('img_principal_base64', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_nome'), 'hotels', ['nome'], unique=True)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.String(length=255), nullable=True),
    sa.Column('data_fim', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_index(op.f('ix_reservas_id_hotel'), 'reservas', ['id_hotel'], unique=False)
    op.create_index(op.f('ix_reservas_id_usuario'), 'reservas', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_celular'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reservas_id_usuario'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id_hotel'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_hotels_nome'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_galeria_hotel_id_hotel'), table_name='galeria_hotel')
    op.drop_index(op.f('ix_galeria_hotel_id'), table_name='galeria_hotel')
    op.drop_table('galeria_hotel')
    op.drop_index(op.f('ix_favoritos_id_usuario'), table_name='favoritos')
    op.drop_index(op.f('ix_favoritos_id_hotel'), table_name='favoritos')
    op.drop_index(op.f('ix_favoritos_id'), table_name='favoritos')
    op.drop_table('favoritos')
    # ### end Alembic commands ###
